version: '3'
services:
  database:
    image: mysql:5.7
    container_name: goldenpath-database
    environment:
      MYSQL_DATABASE: goldenpath
      MYSQL_USER: goldenpathUser
      MYSQL_PASSWORD: goldenpathUserPassword
      MYSQL_ROOT_PASSWORD: rootPassword
    ports:
      - '3306:3306'
    command: --character-set-server=utf8mb4 --default-authentication-plugin=mysql_native_password
