## Jwt properties
server:
  port: 8080
  servlet:
    context-path: /goldenpath/api/v1
app:
  jwtSecret: lola.tech.java.team
  jwtExpirationInMs: 604800000
## Spring boot actuator properties
management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
        exclude:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goldenpath
    username: goldenpathUser
    password: goldenpathUserPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: false
#logging:
#  level:
#    org:
#      springframework:
#        security:
#          web:
#            FilterChainProxy: DEBUG